# Generated by Django 5.1 on 2024-08-31 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envs', '0002_env_access_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='env',
            name='api_requests',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='env',
            name='createdAt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='env',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
